package api
import("crypto/rand";"encoding/hex";"encoding/json";"errors";"net/http";"strings";"github.com/jimlucas/zbx-ssh-gateway/internal/gateway")
type Server struct{Manager *gateway.Manager;Token string;MaxBody int64}
type executeRequest struct{Target string `json:"target"`;Operation string `json:"operation"`;Parameters map[string]string `json:"parameters,omitempty"`}
type response struct{RequestID string `json:"request_id"`;Status string `json:"status"`;Value string `json:"value,omitempty"`;Stdout string `json:"stdout,omitempty"`;Stderr string `json:"stderr,omitempty"`;ExitCode int `json:"exit_code,omitempty"`;DurationMS int64 `json:"duration_ms,omitempty"`;Error string `json:"error,omitempty"`}
func(s *Server)Handler()http.Handler{m:=http.NewServeMux();m.HandleFunc("/api/v1/health",func(w http.ResponseWriter,r *http.Request){write(w,200,map[string]any{"status":"ok","active_requests":s.Manager.ActiveCount()})});m.HandleFunc("/api/v1/execute",s.execute);return m}
func(s *Server)execute(w http.ResponseWriter,r *http.Request){if r.Method!="POST"{write(w,405,response{Status:"error",Error:"method not allowed"});return};if s.Token!=""&&strings.TrimPrefix(r.Header.Get("Authorization"),"Bearer ")!=s.Token{write(w,401,response{Status:"error",Error:"unauthorized"});return};r.Body=http.MaxBytesReader(w,r.Body,s.MaxBody);d:=json.NewDecoder(r.Body);d.DisallowUnknownFields();var q executeRequest;if err:=d.Decode(&q);err!=nil{write(w,400,response{Status:"error",Error:"invalid request"});return};id:=newID();res,err:=s.Manager.Submit(r.Context(),gateway.Request{ID:id,Target:q.Target,Operation:q.Operation,Parameters:q.Parameters});if err!=nil{code:=502;if errors.Is(err,gateway.ErrQueueFull){code=503};write(w,code,response{RequestID:id,Status:"error",Error:err.Error()});return};write(w,200,response{RequestID:id,Status:"ok",Value:res.Value,Stdout:res.Stdout,Stderr:res.Stderr,ExitCode:res.ExitCode,DurationMS:res.Duration.Milliseconds()})}
func newID()string{b:=make([]byte,8);_,_=rand.Read(b);return hex.EncodeToString(b)}
func write(w http.ResponseWriter,c int,v any){w.Header().Set("Content-Type","application/json");w.WriteHeader(c);_=json.NewEncoder(w).Encode(v)}
